#!/bin/bash

go fmt ./...
golint .
go test ./... -tags=unit -failfast
# shellcheck disable=SC2181
if [ $? != 0 ]
then
    echo "Committed code break unit tests"
    exit 1
fi

go test ./... -tags=stripe -failfast -config=ABS_PATH/config.json
# shellcheck disable=SC2181
if [ $? != 0 ]
then
    echo "Committed code break Stripe tests"
    exit 1
fi
