name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13rc2
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Swagger - Installation
        run: |
          export GOPATH="$HOME/go"
          go get -u github.com/swaggo/swag/cmd/swag

      - name: Swagger - Init
        run: swag init

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Config
        run: |
          cp config.json.dist config.json
          sed -i 's/pk_XXX/${{ secrets.STRIPE_PK }}/g' config.json
          sed -i 's/sk_XXX/${{ secrets.STRIPE_SK }}/g' config.json

      - name: Tests - Unit
        run: go test ./... -failfast -tags=unit

      - name: Tests - Stripe
        run: go test ./... -failfast -tags=stripe -config=/data/config.json

      - name: Build
        run: go build -v .
